### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by inkomomutane** [laravel-json-api/docs#10]
Hi @lindyhopchris ,
First of all I have to thank this package, it has been useful for me and I have a suggestion.
how about adding translation to it?
Sometimes I have to suggest to my friends or collaborators to use this package, but they always say it is difficult to use because the docs are only in English.

so I can take the time to translate the docs to at least European Portuguese, if you wish of course.

**Comment by lindyhopchris** [comment]
Hey! Thanks, glad to hear it has been a useful package.

That is very kind of you to offer translations for the docs. I'm slightly reluctant for two reasons:

1. I'm about to do a fairly big re-wiring of the package to support the Atomic Operations extension. So I'm not sure it's worth spending the time translating the docs when there might be a lot of changes coming up. 
2. I'm not sure how I'd maintain the docs once they are translated? I.e. I fairly frequently have to put changes in, and it'd be difficult for me to maintain if there's translations.

Hope that makes sense! Let me know if you have any comments on those points.

**Comment by lindyhopchris** [comment]
I'm going to close this issue for the reasons detailed above. Thank you for the offer, it is appreciated and I'm sorry it's not really practical right now.
