### ISSUE TITLE
Wrong laravel-json-api/boolean-softdeletes package name

### ISSUE THREAD

**Issue by enrikqose** [laravel-json-api/docs#8]
On documentation page for [Boolean Soft-Deletes](https://laraveljsonapi.io/docs/2.0/schemas/soft-deleting.html#boolean-soft-deletes) the command to install the package is shown as 
`composer require laravel-json-api/boolean-soft-deletes
`
while the actual command is
`composer require laravel-json-api/boolean-softdeletes
`

**Comment by lindyhopchris** [comment]
Thanks for reporting, all fixed now.
